# Generated by Django 4.0.4 on 2022-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_clientes_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
